version: '3'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 4G

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1433:1433"

  mvc:
    image: "${CONTAINER_TAG}"
    domainname: "${CONTAINER_FQDN_PREFIX}"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 4G


    environment:
      - ConnectionStrings__ProductDB=${SQLSERVER_CONNECTION_STRING}

    ports:
      - "80:80"
    depends_on:
      - sqlserver