name: UAT IaC and deployment jobs

on:
  pull_request:
    types: [labeled]

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency: uat-pr-${{ github.event.pull_request.number }}

env:
  AZURE_RESOURCE_GROUP: rg-exampleapp-uat-pr-${{ github.event.pull_request.number }}
  AZURE_LOCATION: westeurope
  AZURE_CONTAINER_REGISTRY: crexampleappuatpr${{ github.event.pull_request.number }}
  AZURE_CONTAINER_REGISTRY_URL: crexampleappuatpr${{ github.event.pull_request.number }}.azurecr.io
  CONTAINER_TAG: crexampleappuatpr${{ github.event.pull_request.number }}.azurecr.io/exampleapp:latest
  CONTAINER_INSTANCE: ciexampleappuatpr${{ github.event.pull_request.number }}
  CONTAINER_FQDN_PREFIX: exampleappuatpr${{ github.event.pull_request.number }}
  CONTAINER_PORT: 5000

jobs:
  build-and-deploy-uat:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy') &&
      ! contains(github.event.pull_request.labels.*.name, 'spinup') &&
      ! contains(github.event.pull_request.labels.*.name, 'teardown')
    steps:
      - name: Update PR Comment to indicate start
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Deploying ..._

            To **cancel**, go to **[workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Determine if environment created
        run: |
          if [ $(az group exists -n ${{ env.AZURE_RESOURCE_GROUP }}) == "true" ]
          then
            echo "env_created=1" >> $GITHUB_ENV
          else
            echo "env_created=0" >> $GITHUB_ENV
            echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV
          fi

      - name: Show failure in sticky comment if environment does not exist
        if: ${{ env.env_created == 0 }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Deployment failed!_

            Deployment failed on ${{ env.current_time }}

            Environment does not exist.

            Spinup an environment and then deploy.

        # If environment does not exist, then exit with error code 1.
        # This error code appears to be a "catchall for general errors"
        # that are a result of "impermissible operations"
      - name: Fail if environment does not exist
        if: ${{ env.env_created == 0 }}
        run: |
          echo "::error ::Cannot deploy because environment does not exist"
          exit 1

      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install -g bower
      - run: bower install
      - run: dotnet publish -c Release -o dist
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.CONTAINER_TAG }}

      - name: Login to ACR instance
        run: az acr login --name ${{env.AZURE_CONTAINER_REGISTRY}}
      - name: Publish Docker container
        run: docker push ${{ env.CONTAINER_TAG }}

      - name: Create or restart container instance
        # we need to delete the existing ACI instance (the container group) first
        # as it needs to be done before Azure would allow memory/cpu reservation of a container to be altered.
        #
        # docker compose down no good for this if the container group doesn't already exist.
        # Hence to give ourselves a well-known name, instead of the docker compose default of
        # name of the containing directory, we have delcare the name of the ACI instance
        # in an environment variable. We pass it to az containe delete which does NOT return
        # an error if the container instance doesn't already exist.
        # We then also pass it to docker compose up in parameter --project-name
        run: |
          az container delete -n ${{ env.CONTAINER_INSTANCE }} -g ${{ env.AZURE_RESOURCE_GROUP }} --yes

          az deployment group create -g ${{ env.AZURE_RESOURCE_GROUP }} --template-file .github/workflows/uat/uat_deploy_aci.bicep --parameters name='${{ env.CONTAINER_INSTANCE }}' dnsNameLabel='${{env.CONTAINER_FQDN_PREFIX}}' mvcRegistryName='${{env.AZURE_CONTAINER_REGISTRY}}' mvcImage='${{env.CONTAINER_TAG}}' sqlServerSAPassword='${{secrets.UAT_SQLSERVER_PASSWORD}}' sqlServerConnectionString='${{secrets.UAT_SQLSERVER_CONNECTION_STRING}}' port='${{env.CONTAINER_PORT}}' mvcRegistryServer='${{env.AZURE_CONTAINER_REGISTRY_URL}}' managedIdentityForMvcRegistry='${{secrets.AZURE_MANAGED_IDENTITY_URI_FOR_ACR_ACCESS}}'

      - name: Remove deploy label from PR
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            deploy

      - name: Get current datetime to write in PR comment
        if: always()
        run: |
          echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV

      - name: Update PR comment to indicate failure
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Deployment failed!_

            Deployment failed on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR comment to indicate cancellation
        if: cancelled()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Deployment cancelled!_

            Deployment cancelled on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR Comment to indicate success
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Deployed_

            UAT environment deployed on ${{ env.current_time }}

            Deployed ${{ github.sha }} to <http://${{ env.CONTAINER_FQDN_PREFIX }}.${{ env.AZURE_LOCATION }}.azurecontainer.io:${{ env.CONTAINER_PORT }}>

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

  spinup-uat:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'spinup') &&
      ! contains(github.event.pull_request.labels.*.name, 'deploy') &&
      ! contains(github.event.pull_request.labels.*.name, 'teardown')

    steps:
      - name: Remove  deploy label from PR if it exists
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            deploy

      - name: Update PR Comment to indicate start
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Spinning up ..._

            To **cancel**, go to **[workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete resource group if it exists
        if: success()
        run: |
          if [ $(az group exists -n ${{ env.AZURE_RESOURCE_GROUP }}) == "true" ]
          then
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --yes
          fi

      - name: Create resource group
        if: success()
        run: az group create --name ${{env.AZURE_RESOURCE_GROUP}} --location ${{env.AZURE_LOCATION}}

      - name: Create Docker registry
        if: success()
        run: |
          az acr create --name ${{env.AZURE_CONTAINER_REGISTRY}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --sku Basic

      - name: Remove spinup label from PR
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            spinup

      - name: Get current datetime to write in PR comment
        if: always()
        run: |
          echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV

      - name: Update PR comment to indicate failure
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Spin up failed!_

            Spin up failed on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR comment to indicate cancellation
        if: cancelled()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Spin up cancelled!_

            Spin up cancelled on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR Comment
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Created_

            UAT environment created on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

  teardown-uat:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'teardown') &&
      ! contains(github.event.pull_request.labels.*.name, 'spinup') &&
      ! contains(github.event.pull_request.labels.*.name, 'deploy')

    steps:
      - name: Update PR Comment to indicate start
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Tearing down ..._

            To **cancel**, go to **[workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete resource group if it exists
        if: success()
        run: |
          if [ $(az group exists -n ${{ env.AZURE_RESOURCE_GROUP }}) == "true" ]
          then
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --yes
          fi

      - name: Remove teardown label from PR
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            teardown

      - name: Get current datetime to write in PR comment
        if: always()
        run: |
          echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV

      - name: Update PR comment to indicate failure
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Teardown failed!_

            Teardown failed on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR comment to indicate cancellation
        if: cancelled()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Teardown cancelled!_

            Teardown cancelled on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

      - name: Update PR Comment to indicate success
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Torn down_

            UAT environment torn down on ${{ env.current_time }}

            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.

  validate-labels:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    # There are three labels - deploy, spinup and teardown - that we
    # only want to appeat one at a time. Hence we want to exclude
    # any pair of these (which includes the case of all three) appearing
    # on the pull request. There are 3C2 = 3 such pairs.
    if: (contains(github.event.pull_request.labels.*.name, 'spinup') &&
      contains(github.event.pull_request.labels.*.name, 'deploy')) ||
      (contains(github.event.pull_request.labels.*.name, 'spinup') &&
      contains(github.event.pull_request.labels.*.name, 'teardown')) ||
      (contains(github.event.pull_request.labels.*.name, 'deploy') &&
      contains(github.event.pull_request.labels.*.name, 'teardown'))
    steps:
      - name: Update PR Comment to say command combination is invalid
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Invalid command labels!_

            Only **one** command label, i.e. only one of **spinup**, **deploy** or **teardown**, may be placed on the pull request at a time.

            This pull request contains more than one of these labels.
