name: Spinup or Teardown UAT environment

on:
  pull_request:
    types: [labeled]

concurrency: uat-pr-${{ github.event.pull_request.number }}

env:
  AZURE_RESOURCE_GROUP: rg-exampleapp-uat-pr-${{ github.event.pull_request.number }}
  AZURE_LOCATION: westeurope
  AZURE_CONTAINER_REGISTRY: crexampleappuatpr${{ github.event.pull_request.number }}

jobs:
  spinup-uat:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'spinup')

    steps:
      - name: Remove  labels from PR
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            deployed
            uat created

      - name: Update PR Comment to indicate start
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Spinning up ..._

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource group if it exists
        if: success()
        run: |
          if [ $(az group exists -n ${{ env.AZURE_RESOURCE_GROUP }}) == "true" ]
          then
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --yes
          fi

      - name: Create resource group
        if: success()
        run: az group create --name ${{env.AZURE_RESOURCE_GROUP}} --location ${{env.AZURE_LOCATION}}

      - name: Create Docker registry
        if: success()
        run: |
          az acr create --name ${{env.AZURE_CONTAINER_REGISTRY}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --sku Basic

      - name: Label the PR with 'uat created'
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "uat created"

      - name: Remove 'spinup' label from PR
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "spinup"

      - name: Get current datetime to write in PR comment
        run: |
          echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV

      - name: Update PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Created_

            UAT environment created on ${{ env.current_time }}

  teardown-uat:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'teardown')

    steps:
      - name: Update PR Comment to indicate start
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Tearing down ..._

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource group if it exists
        if: success()
        run: |
          if [ $(az group exists -n ${{ env.AZURE_RESOURCE_GROUP }}) == "true" ]
          then
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --yes
          fi

      - name: Remove IaC labels from PR
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            deployed
            teardown
            uat created

      - name: Get current datetime to write in PR comment
        run: |
          echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV

      - name: Update PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: uat
          message: |
            # UAT Environment - _Torn down_

            UAT environment torn down on ${{ env.current_time }}
