name: Spinup or Teardown UAT environment

on:
  pull_request:
    types: [labeled]

concurrency: uat-pr-${{ github.event.pull_request.number }}

env:
  AZURE_RESOURCE_GROUP: rg-exampleapp-uat-pr-${{ github.event.pull_request.number }}
  AZURE_LOCATION: westeurope
  AZURE_CONTAINER_REGISTRY: crexampleappuatpr${{ github.event.pull_request.number }}
  CONTAINER_TAG: crexampleappuatpr${{ github.event.pull_request.number }}.azurecr.io/exampleapp:latest
  AZURE_CONTAINER_INSTANCE: ciexampleappuatpr${{ github.event.pull_request.number }}
  CONTAINER_FQDN_PREFIX: exampleappuatpr${{ github.event.pull_request.number }}
  SQLSERVER_PASSWORD: ${{secrets.UAT_SQLSERVER_PASSWORD}}
  SQLSERVER_CONNECTION_STRING: ${{secrets.UAT_SQLSERVER_CONNECTION_STRING}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'uat created') &&
      contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - name: Remove deployed label if it exists
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: deployed
          fail-on-error: false

      - uses: actions/checkout@v3
      - run: npm install
      - run: dotnet publish -c Release -o dist
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.CONTAINER_TAG }}
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to ACR instance
        run: az acr login --name ${{env.AZURE_CONTAINER_REGISTRY}}
      - name: Publish Docker container
        run: docker push ${{ env.CONTAINER_TAG }}

      - name: Install Docker Compose CLI
        run: >
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: "Docker login azure"
        run: docker login azure --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Create docker context
        run: |
          docker context create aci myacicontext --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Create or restart container instance
        # we docker compose down first as it needs to be done before Azure would allow
        # memory/cpu reservation of a container to be altered
        run: |
          docker --context myacicontext compose -f .github/workflows/uat/docker-compose-uat.yml down
          docker --context myacicontext compose -f .github/workflows/uat/docker-compose-uat.yml up

      - name: Remove deploy label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: deploy
          fail-on-error: false

      - name: Label the PR with 'deployed'
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: deployed
          fail-on-error: false
